"""core_data_model

Revision ID: ee260148b4f6
Revises: 0001
Create Date: 2026-09-14 01:55:19.157015

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('local_smtp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_last_rotated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_smtp_users'))
    )
    op.create_index(op.f('ix_local_smtp_users_username'), 'local_smtp_users', ['username'], unique=True)
    op.create_table('upstream_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('tls_mode', sa.Enum('starttls', 'implicit', name='tls_mode'), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', sa.Enum('unknown', 'success', 'failure', name='test_result'), nullable=True),
    sa.Column('last_test_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upstream_accounts'))
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_admin_sessions_admin_user_id_admin_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions'))
    )
    op.create_index(op.f('ix_admin_sessions_admin_user_id'), 'admin_sessions', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_audit_log_admin_user_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_action_ip_ts', 'audit_log', ['action', 'ip_address', 'timestamp'], unique=False)
    op.create_index('ix_audit_log_action_target_ts', 'audit_log', ['action', 'target_type', 'target_id', 'timestamp'], unique=False)
    op.create_table('config_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('validation_result', sa.Enum('pass', 'fail', name='validation_result'), nullable=False),
    sa.Column('validation_detail', sa.String(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('reload_triggered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_admin_id'], ['admin_users.id'], name=op.f('fk_config_generations_triggered_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_generations'))
    )
    op.create_table('mail_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('local_smtp_user_id', sa.Integer(), nullable=True),
    sa.Column('envelope_sender', sa.String(length=320), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('upstream_account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'deferred', 'bounced', 'rejected', name='mail_status'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_smtp_user_id'], ['local_smtp_users.id'], name=op.f('fk_mail_log_local_smtp_user_id_local_smtp_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upstream_account_id'], ['upstream_accounts.id'], name=op.f('fk_mail_log_upstream_account_id_upstream_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_log'))
    )
    op.create_index('ix_mail_log_envelope_sender', 'mail_log', ['envelope_sender'], unique=False)
    op.create_index('ix_mail_log_local_smtp_user_id', 'mail_log', ['local_smtp_user_id'], unique=False)
    op.create_index(op.f('ix_mail_log_queue_id'), 'mail_log', ['queue_id'], unique=False)
    op.create_index('ix_mail_log_status', 'mail_log', ['status'], unique=False)
    op.create_index('ix_mail_log_timestamp', 'mail_log', ['timestamp'], unique=False)
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('upstream_account_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upstream_account_id'], ['upstream_accounts.id'], name=op.f('fk_senders_upstream_account_id_upstream_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_senders'))
    )
    op.create_index(op.f('ix_senders_address'), 'senders', ['address'], unique=True)
    op.create_index(op.f('ix_senders_upstream_account_id'), 'senders', ['upstream_account_id'], unique=False)
    op.create_table('user_sender_permissions',
    sa.Column('local_smtp_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_admin_id'], ['admin_users.id'], name=op.f('fk_user_sender_permissions_granted_by_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['local_smtp_user_id'], ['local_smtp_users.id'], name=op.f('fk_user_sender_permissions_local_smtp_user_id_local_smtp_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], name=op.f('fk_user_sender_permissions_sender_id_senders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('local_smtp_user_id', 'sender_id', name=op.f('pk_user_sender_permissions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sender_permissions')
    op.drop_index(op.f('ix_senders_upstream_account_id'), table_name='senders')
    op.drop_index(op.f('ix_senders_address'), table_name='senders')
    op.drop_table('senders')
    op.drop_index('ix_mail_log_timestamp', table_name='mail_log')
    op.drop_index('ix_mail_log_status', table_name='mail_log')
    op.drop_index(op.f('ix_mail_log_queue_id'), table_name='mail_log')
    op.drop_index('ix_mail_log_local_smtp_user_id', table_name='mail_log')
    op.drop_index('ix_mail_log_envelope_sender', table_name='mail_log')
    op.drop_table('mail_log')
    op.drop_table('config_generations')
    op.drop_index('ix_audit_log_action_target_ts', table_name='audit_log')
    op.drop_index('ix_audit_log_action_ip_ts', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_admin_user_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_table('upstream_accounts')
    op.drop_index(op.f('ix_local_smtp_users_username'), table_name='local_smtp_users')
    op.drop_table('local_smtp_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
