"""mail_log_ingest_state

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 09:50:22.073648

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_log_ingest_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('byte_offset', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_log_ingest_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_log_ingest_state')
    # ### end Alembic commands ###
