"""config_generation_maps_checksum

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-14 10:14:47.438565

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_generations', sa.Column('maps_checksum', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_generations', 'maps_checksum')
    # ### end Alembic commands ###
